name: Deploy to SFTP

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - { host: "xb780382.xbiz.jp", username: "xb780382", port: 10022 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #リポジトリのソースを取得

      - name: test
        run: echo "⭐️ ${{matrix.server.host}} ${{matrix.server.username}} ${{matrix.server.port}}"

      - name: SFTP deploy to ${{ matrix.server }}
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ matrix.server.host }}
          username: ${{ matrix.server.username }}
          port: ${{ matrix.server.port }}
          privateKey: ${{ secrets.XSERVER_SFTP_PRIVATE_KEY }}   # 鍵認証
          passphrase: ${{ secrets.XSERVER_SFTP_PASSPHRASE }}  # 鍵にパスフレーズがある場合
          localDir: "./"
          remoteDir: "/home/xb780382/xb780382.xbiz.jp/public_html"
          compress: true
          forceUpload: true
          # dryRun: true
